name: Delete stale branches

on:
  schedule:
    - cron: "0 11 * * *" # Runs every day at 11 AM (UTC)

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branches not updated for 6 months
        run: |
          # Get all branches that haven't been updated for 6 months
          for branch in $(git branch -r --sort=-committerdate | grep -v '\->' | sed 's/origin\///'); do
            last_commit_date=$(git show -s --format=%ci origin/$branch)
            six_months_ago=$(date --date='6 months ago' +%Y-%m-%d)
            
            # If the last commit date is older than 6 months, delete the branch
            if [[ "$last_commit_date" < "$six_months_ago" ]]; then
              echo "Deleting branch $branch"
              git push origin --delete $branch
            fi
          done
