name: Prevent Merges During Code Freeze

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  prevent-merging:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Freeze
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          FREEZE_START="2024-09-30"
          FREEZE_END="2024-10-07"

          if [[ "$CURRENT_DATE" > "$FREEZE_START" && "$CURRENT_DATE" < "$FREEZE_END" ]]; then
            echo "Code freeze is active. Merges are not allowed."
            exit 1
          fi
